baseurl = "/"
ignoreFiles = ["\\.Rmd$", "_files$"]

languageCode = "en-us"
title = "R Views"
# Enable comments by entering your Disqus shortname
disqusShortname = "jkr216"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
    # Tell me who you are
    author = "JKR"
    bio = "A reproducible finance site by <img src='/css/images/rstudio.svg' width=90 alt='RStudio' />"
    location = "Atlanta, GA"
    site_description = "A site dedicated to reproducible finance."
    copyright  = "Reproducible Finance, LLC All Rights Reserved."
    avatar = "css/images/logo.png"
    logo = "css/images/logo.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    fullURL = "www.reproduciblefinance.com"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option to
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = true
    label  = "About"
    link   = "about/"

[[params.menu]]
    before = true
    label  = "Contributors"
    link   = "contributors/"
    
[[params.menu]]
    before = true
    label  = "Projects"
    link   = "projects/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/jkregenstein"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "jkr216"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "regregenstein"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "jkregenstein"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = false
    tag_cloud = true
