baseurl = "/"
ignoreFiles = ["\\.Rmd$", "_files$"]
relativeurls = true

languageCode = "en-us"
title = "R Views"
# Enable comments by entering your Disqus shortname
disqusShortname = "rrstudio"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-20375833-3"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
    # Tell me who you are
    author = "R Views"
    bio = "An R community blog edited by RStudio"
    location = "Boston, MA"
    site_description = "An R community blog edited by RStudio"
    copyright  = "RStudio, Inc. All Rights Reserved."
    avatar = "css/images/avatar.png"
    logo = "css/images/logo.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/rstudio"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "rstudio"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "../company/rstudio-inc"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "pages/RStudio-Inc/267733656584415"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "rstudio"

# Enable and disable widgets for the right sidebar
[params.widgets]
    marketo = true
    recent_articles = true
    categories = true
    tags = false
    tag_cloud = true
