---
title: 10,000 CRAN Packages
author: Joseph Rickert
date: '2017-01-06'
categories: [R Packages, News, R Language]
tags: [R]
draft: no
---

The R package system continues to expand as the number of packages on CRAN is about to blow through the 10,000 mark sometime soon. This is astonishing! Not only are new packages arriving at a rate of about 190 per month, but CRAN itself continues to tick along like a well-oiled machine, 24 by 7\. We all owe a great deal of gratitude to the CRAN maintainers, and to the Bioconductor team as well, who are maintaining more than 1,200 packages.

My source for following new CRAN packages is Dirk Eddelbuettel's [CRANberries site](http://dirk.eddelbuettel.com/cranberries/). The [CRAN:New](http://dirk.eddelbuettel.com/cranberries/cran/new/) tab will show you the details for the current crop of new packages.

The following function pulls information from CRANberries and returns a vector containing the number of new packages submitted to CRAN in a specified time period.

<iframe src="https://beta.rstudioconnect.com/content/2324/10000_cran_packages_block1.html" width="1000px" height="490px"></iframe>

To save you the trouble of running the function, here is a vector containing the number of new packages for the 108 months from January 2008 through December 2016.

<iframe src="https://beta.rstudioconnect.com/content/2326/10000_cran_packages_block2.html" width="1000px" height="230px"></iframe>

Let's plot the data as a time series.

<iframe src="https://beta.rstudioconnect.com/content/2327/10000_cran_packages_block3.html" width="1000px" height="780px"></iframe>

and forecast the expected number of new packages for the next several months.

<iframe src="https://beta.rstudioconnect.com/content/2328/10000_cran_packages_block4.html" width="1000px" height="280px"></iframe>

By my count, CRAN ended 2016 with 9,823 packages. So, if the number of new packages for January equals at least the low value forecast for the 95th percentile, CRAN will reach the 10,000 package mark this month!
