---
title: Some R News
date: '2017-01-13'
author: Joseph Rickert
categories: [Community, News, R Language]
tags: [R]
draft: no
---

Here are a few things of some interest in the R world:

*   The [Gordon and Betty Moore Foundation](http://www.moore.org) has joined the R Consortium! This is a very positive development for the R Consortium and the R Community in general. The Moore Foundation has been a positive force for supporting technology that can make a real difference in people’s lives since its foundation in 2000 with an endowment of over $6 billion. The grant from the Moore Foundation brings considerable prestige and resources to the R Consortium. And the direct participation of Chris Mentzel, program director of the Moore Foundation’s Data-Driven Discovery Initiative, will lend his expertise to both the R Consortium’s Board of Directors and Infrastructure Steering Committee. (The Data-Driven Discovery Initiative, which supports efforts to develop tools and techniques to harness large, complex data sets, is backed by a $60 million budget.) For more information, see the R Consortium’s [announcement](http://news/2017/01/11/gordon-and-betty-moore-foundation-joins-r-consortium-to-encourage-development-maintenance-and-distribution-of-r-software).
*   [rstudio::conf](https://www.rstudio.com/conference/), the first RStudio-organized conference devoted to “all things R and RStudio”, kicked off today in Orlando following two days of training and workshops. The preliminary numbers for the conference are very encouraging. Over 200 R users attended the workshops, while approximately 400 people are expected to attend the conference itself. The two new workshops developed for rstudio::conf, “Intermediate Shiny” and “Master the Tidyverse” are expected to be offered at various locations later this year. All of the conference presentations should be available online in a few weeks.
*   The R Consortium’s Information Steering Committee (ISC) first [call for proposals](https://www.r-consortium.org/blog/2016/12/06/call-for-proposals) for 2017 will close on midnight February 10th. There is still time to get your [proposal](https://www.r-consortium.org/projects/submit-proposal) reviewed - and possibly funded - by the ISC.
*   The next satRday event will be held in Cape Town South Africa on February 18th.
*   New York R will be held on April 21st and 22nd. The website should be up soon.
*   [R/Finance 2017](http://www.rinfinance.com/), the ninth annual R/Finance conference, is scheduled for May 19th and 20th in Chicago. Over the past eight years, R/Finance has attained a superb record for technical excellence and for offering a quality R Community experience. I expect the trend to continue. Registration is not yet open, but the [call for papers](http://www.rinfinance.com/#cfp) will be open until February 28th.
*   Registration for useR! 2017 is open, and the conference is already filling up! This is the premier international conference for the R Community. If you can be in Brussels this summer, don’t miss the opportunity to attend.
