---
title: Looking Forward to R/Finance 2017
author: Joseph Rickert
date: '2017-05-12'
slug: ''
categories: 
  - R Language
  - Finance
  - Community
  - Events
tags: 
  - R / Finance 2017
  - Finance
  - R Conferences
summary: ''
---

[R / Finance 2017](http://www.rinfinance.com/) starts next Friday, and once again, I am excited about going. It's true that there are quite a few fun and informative R gatherings these days, but R / Finance is a "big deal" because it is the "real deal". Finance has been, and remains, one of the driving applications underlying the R language. (A glance at the CRAN Task Views for [Finance](https://cran.r-project.org/web/views/Finance.html) and [Time Series](https://cran.r-project.org/web/views/TimeSeries.html) will give you an idea of the depth and extent of the work done in this area since the early days of R.) But beyond that, there is an intensity about people who write algorithms under time pressure with money on the line. R / Finance provides a window to this world by running a small, focused, single-track conference where a third of the attendees are going to be experts in the field, and the speakers include people whose professional lives either shaped the practice of financial analytics or are influencing the direction of R.

Keynote speaker, [David DeMers](https://www.linkedin.com/in/david-demers-3093a/) arrived early enough at the [Prediction Company](http://www.predict.com/), the legendary analytics quant firm founded by [Doyne Farmer](http://tuvalu.santafe.edu/~jdf/About%20Me.html) and the other Chaos Theory geniuses immortalized in [*The Eudaemonic* Pie](https://www.amazon.com/Eudaemonic-Pie-Thomas-Bass-ebook/dp/B06XGM7K64/ref=sr_1_1?ie=UTF8&qid=1494364195&sr=8-1&keywords=eudaemonic+pie), to get his own paragraph in Thomas Bass' follow-up read: [*The Predictors*](https://www.amazon.com/Predictors-Maverick-Physicists-Theory-Fortune/dp/0805057579/ref=sr_1_1?ie=UTF8&qid=1494364439&sr=8-1&keywords=The+predictors).

> Arriving at the same time [1995] as Stephen [Pope] is the company's new researcher, David DeMers, a Falstaffian character with a walrus mustache, a thatch of gray hair parted in the middle, and the useful skills of a professional bridge player. Given to wearing wild, floral-print surfer jammies and T-shirts saying, "I am a professional. Do not try this at home," DeMers shares an office with William [Finnoff], where his round, cherubic face is the perfect antidote to William's Germanic angst. Born in 1954 into a family of French Canadian ancestry, DeMers, the son of an aerospace engineer, has a B.S. from Stanford in math. He has an M.B.A. from the University of California at Los Angles. He has another degree from UCLA in law. And, finally he has a Ph.D. in computer science from UC San Diego, where he used neural networks to control robot arms.
  DeMers's fist assignment at the Prediction Company is to plug the oil leak. The prices at which their contracts are being traded diverge dramatically from the prices quoted over the satellite feed. . .
  
[Szilard Pafka](https://github.com/szilard) ([No-Bullshit Data Science](https://speakerdeck.com/szilard/machine-learning-meetup-febr-2017)), the conference's other keynote speaker, balances DeMers' quant history with a heavy dose of R reality. Szilard is a no-nonsense, data-driven kind of guy with little tolerance for the hype that drives much of the Big Data, data science marketing machine. Szilard has been a force in the R Community, organizing [meetups](https://www.meetup.com/Data-Science-Los-Angeles/), speaking, and spending a good bit of his free time [benchmarking R](http://datascience.la/benchmarking-random-forest-implementations/) and [other technologies](https://github.com/szilard/benchm-ml).

Here is a video of Szilard speaking last year at useR!.

<iframe src="https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/Size-of-Datasets-for-Analytics-and-Implications-for-R/player" width="960" height="540" allowFullScreen frameBorder="0"></iframe>

Other speakers of note include [David Smith](https://channel9.msdn.com/events/useR-international-R-User-conference/useR2016/R-at-Microsoft), [Bryan Lewis](https://www.youtube.com/watch?v=PM7O6EGakKY&feature=youtu.be), [Thomas Harte](https://www.linkedin.com/in/thomas-harte-415a3413/), [Seoyoung Kim](https://www.scu.edu/business/finance/faculty/kim/), who [spoke recently](https://github.com/joseph-rickert/BARUG/blob/master/skim_BARUG_20170411.pdf) at the [Bay Aeea useR Group](https://www.meetup.com/R-Users/), and RStudio's own [Jonathan Regenstein](https://www.linkedin.com/in/regregenstein/), who has been setting the standard for blogging about R and Finance. Jonathan provides the nuts and bolts details on how to use the latest R tools with data from multiple sources to generate insight and share it in reproducible workflows. If you are looking to get started with using R for Finance or just want to prep for the R  / Finance conference, you can't do any better than working through the posts in Jonathan's [Reproducible Finance with R](https://rviews.rstudio.com/categories/reproducible-finance-with-r/) series.
